# coding: utf-8

# flake8: noqa
"""
    ATIP AI Search API

    This API provides AI search functionalities: summary search and department recommendation.    Use the following code to authorize: ` nTsVPfUb89Ize/1DVSx2xKjLltOagND80lEfHaVB3fGT8CQEF7e9Lw== `  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: atip-support@lixar.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.combined_result import CombinedResult
from swagger_client.models.department_recommendation import DepartmentRecommendation
from swagger_client.models.department_recommendation_result import DepartmentRecommendationResult
from swagger_client.models.summary_document import SummaryDocument
from swagger_client.models.summary_search_result import SummarySearchResult
from swagger_client.models.summary_search_result_response import SummarySearchResultResponse
from swagger_client.models.summary_search_result_response_header import SummarySearchResultResponseHeader
from swagger_client.models.summary_search_result_response_header_params import SummarySearchResultResponseHeaderParams
